### ISSUE TITLE
apihost name does not tolerate comment

### ISSUE THREAD

**Issue by rabbah** [adobe/aio-cli-plugin-runtime#90]
**Describe the bug**
Create a .wskprop file with
```
AUTH=23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP
APIHOST=https://localhost #:3233
```

Then:
```
./bin/run runtime:namespace:get  -i -v
  aio-cli-config reading config: /Users/rabbah/.config/aio +0ms
  aio-cli-config reading config: /Users/rabbah/projects/aio-cli-plugin-runtime/.aio +2ms
  aio-cli-plugin-runtime { apiversion: 'v1',
  aio-cli-plugin-runtime   apihost: 'https://localhost #:3233',
  aio-cli-plugin-runtime   api_key:
  aio-cli-plugin-runtime    '23bc46b1-71f6-4ed5-8c54-816aa4f8c502:123zO3xZCLrMN6v2BKK1dXYFpXlPkccOFqm12CdAsMgRU4VrNZ9lyGVCGuMDGIwP',
  aio-cli-plugin-runtime   ignore_certs: true } +0ms
  aio-cli-plugin-runtime OpenWhiskError: GET https://localhost/namespaces/_/actions#:3233/api/v1/ Returned HTTP 404 (Not Found) --> "The requested resource could not be found."
  aio-cli-plugin-runtime     at Client.handleErrors (/Users/rabbah/projects/aio-cli-plugin-runtime/node_modules/openwhisk/lib/client.js:216:11)
  aio-cli-plugin-runtime     at params.then.catch.err (/Users/rabbah/projects/aio-cli-plugin-runtime/node_modules/openwhisk/lib/client.js:147:58)
  aio-cli-plugin-runtime     at process._tickCallback (internal/process/next_tick.js:68:7) +48ms
 ›   Error: failed to get the data for a namespace: the requested resource could not be found. (404 Not Found)
 ›     specify --verbose flag for more information
```

Notice the host being used in the URI includes the `# ...` comment from the property file.

**Comment by rabbah** [comment]
Similar to the issue reported here apache/openwhisk-cli#481, a trailing `/` on the API host also causes a failure:

```
> ./bin/run runtime:action:list --apihost https://example.com/
 ›   Error: failed to list the actions: the requested resource could not be found. (404 Not Found)
 ›     specify --verbose flag for more information

this does affect us also. With the --verbose setting, I see:

  aio-cli-plugin-runtime OpenWhiskError: GET https://example.com//api/v1/namespaces/_/actions Returned HTTP 404 (Not Found) --> "The requested resource could not be found."
```
