### ISSUE TITLE
Activations with empty annotations break `aio rt activation list`

### ISSUE THREAD

**Issue by meryllblanchet** [adobe/aio-cli-plugin-runtime#97]
**Describe the bug**
If for some reason, `aio rt activation list` returns some activations with an empty array as value for the annotations field, the command breaks while attempting to display this annotation.

**To Reproduce**
1. Simulate an activation with empty annotation field to be displayed by the command
2. Example of faulty activation object:

`{ activationId: 'xxxxxxx',
  annotations: [],
  name: 'formSubmitTrigger',
  namespace: 'mynamespace-qa',
  publish: false,
  start: 1578904620503,
  statusCode: 0,
  version: '0.0.1' }`

3. Verbose output of the command:

` aio-cli-plugin-runtime { apiversion: 'v1',
  aio-cli-plugin-runtime   apihost: 'https://adobeioruntime.net',
  aio-cli-plugin-runtime   namespace: 'mynamespace-qa',
  aio-cli-plugin-runtime   api_key:
  aio-cli-plugin-runtime    'xxx:yyy' } +0ms
  aio-cli-plugin-runtime TypeError: Cannot read property 'value' of undefined
  aio-cli-plugin-runtime     at Object.get (/Users/username/.nvm/versions/node/v10.14.0/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-cli-plugin-runtime/src/commands/runtime/activation/list.js:67:17)
  aio-cli-plugin-runtime     at rows.data.map.d (/Users/username/.nvm/versions/node/v10.14.0/lib/node_modules/@adobe/aio-cli/node_modules/cli-ux/lib/styled/table.js:48:31)
  aio-cli-plugin-runtime     at Array.map (<anonymous>)
  aio-cli-plugin-runtime     at Table.display (/Users/username/.nvm/versions/node/v10.14.0/lib/node_modules/@adobe/aio-cli/node_modules/cli-ux/lib/styled/table.js:45:30)
  aio-cli-plugin-runtime     at Object.table (/Users/username/.nvm/versions/node/v10.14.0/lib/node_modules/@adobe/aio-cli/node_modules/cli-ux/lib/styled/table.js:263:39)
  aio-cli-plugin-runtime     at ActivationList.run (/Users/username/.nvm/versions/node/v10.14.0/lib/node_modules/@adobe/aio-cli/node_modules/@adobe/aio-cli-plugin-runtime/src/commands/runtime/activation/list.js:97:15)
  aio-cli-plugin-runtime     at process._tickCallback (internal/process/next_tick.js:68:7) +265ms
 ›   Error: failed to list the activations: Cannot read property 'value' of undefined
 ›     specify --verbose flag for more information`

**Expected behavior**
Rather, the command should display successfuly the activations, which have annotation metadata array populated.
It should also display the available metadata of the activations and skip the annotation metadata array if this one is empty.

**Screenshots**
See logs above

**Desktop (please complete the following information):**
Applies for all desktop clients

**Comment by meryllblanchet** [comment]
Fixed by https://github.com/adobe/aio-cli-plugin-runtime/pull/98
